#!/bin/env bash

# color
rooter=$( echo -e '\e[38;5;196m' )
green=$( echo -e '\e[38;5;112m' )
greys=$( echo -e '\e[38;5;249m' )
lgren=$( echo -e '\e[38;5;118m' )
blues=$( echo -e '\e[38;5;75m' )
lblue=$( echo -e '\e[38;5;111m' )
golds=$( echo -e '\e[38;5;220m' )
lgold=$( echo -e '\e[38;5;222m' )
reset=$(echo -e '\e[0m' )


# user with gitrepo

if [[ -n $branch ]]; then  
  PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null)'; 
  PS1='\n${rooter} --(\#)--(\u@\h )-->${reset} ${blues}${reset} ${lblue}\w${reset} ${greys}|   ${PS1_CMD1} |-->${reset} ${golds}${reset} ${golds}\t${reset} \n ${greys}󱞩 ${reset}'
  return
fi


# user without gitrepo

if [[ -z $branch ]]; then  
  PS1='\n${rooter} --(\#)--(\u@\h )-->${reset} ${blues}${reset} ${lblue}\w${reset} ${greys}|-->${reset} ${golds}${reset} ${golds}\t${reset} \n ${greys}󱞩 ${reset}'
  return
fi
