#!/bin/env bash

function raviza_systems() {

  local system="$HOME/.config/bash/systems"

  if [[ $UID == 0 ]];then
    source $system/rooter
  fi

  if [[ $UID != 0 ]];then
    source $system/basher
  fi

  source $system/aliases
}


function raviza_loader() {
  raviza_systems
}

raviza_loader
